# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.3

      - name: Install Haxelibs
        run: |
          haxelib --quiet install lime
          haxelib --quiet install openfl
          haxelib --quiet install flixel 5.5.0
          haxelib --quiet --never run lime setup
          haxelib --quiet install flixel-ui
          haxelib --quiet git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git dev
          haxelib --quiet install polymod 1.7.0
          haxelib --quiet install hscript
          haxelib --quiet install hxcpp-debug-server
          haxelib --quiet install extension-androidtools 1.4.0
          haxelib --quiet git spine https://github.com/jeremyfa/spine-hx.git

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -Dnightly

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.3

      - name: Install Haxelibs
        run: |
          haxelib --quiet install lime
          haxelib --quiet install openfl
          haxelib --quiet install flixel 5.5.0
          haxelib --quiet install flixel-ui
          haxelib --quiet git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git dev
          haxelib --quiet install polymod 1.7.0
          haxelib --quiet install hscript
          haxelib --quiet install hxcpp-debug-server
          haxelib --quiet git spine https://github.com/jeremyfa/spine-hx.git
          haxelib --quiet git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
        shell: cmd

      - name: Compile
        run: haxelib run lime build windows -Dnightly

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin